[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tinykv"
authors = [{name = "Flavio Veloso Soares", email = "flaviovs@magnux.com"}]
license = {file = "LICENSE"}
readme = "README.md"
keywords = ["python", "sqlite", "sqlite3", "key-value store", "kv"]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Topic :: Database",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.11"

dynamic = ["version", "description"]

[project.urls]
Homepage = "https://github.com/flaviovs/tinykv"
Repository = "https://github.com/flaviovs/tinykv"
Issues = "https://github.com/flaviovs/tinykv/issues"

[dependency-groups]
dev = [
  'ruff',
  'flit',
  'mypy',
]

[tool.mypy]
files = "."
python_version = "3.11"
exclude = [".git", ".venv"]
strict = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
pretty = true

[tool.ruff]
line-length = 79
include = ["**/*.py"]

[tool.ruff.format]
skip-magic-trailing-comma = false

[tool.ruff.lint]
extend-select = ["PLC0415"]
external = ["V107"]
select = [
  "E", "F", "I", "B", "UP", "SIM", "RET", "ARG", "RUF", "PTH", "C4", "PIE", "D",
  "TRY", "ERA", "ANN",
]
ignore = ["TRY003", "COM812"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D"]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["traderworkbench"]

[tool.ruff.lint.pydocstyle]
# Explicitly enforce Google-style docstrings instead of PEP 257 standard.
convention = "google"
